export const RecipeMockData = [
  {
    id: 1,
    title: "Mustang Mashed Potatoes",
    subtitle: "Mash your way to a smooth ride",
    cookingTimeInMins: 35,
    ingredients: [
      { ingredient: "Potatoes", amount: 4, unit: "large" },
      { ingredient: "Butter", amount: 4, unit: "tbsp" },
      { ingredient: "Milk", amount: 0.5, unit: "cup" },
      { ingredient: "Salt", amount: 1, unit: "tsp" },
      { ingredient: "Pepper", amount: 0.5, unit: "tsp" },
    ],
    instructions: [
      "Wash and peel 4 large potatoes. Cut them into evenly sized cubes (about 4 cm pieces).",
      "Place the cubed potatoes in a large pot and fill with enough water to cover them by about 2.5 cm. Add a pinch of salt to the water.",
      "Bring the pot to a boil over high heat. Once boiling, reduce the heat to medium and let the potatoes cook for about 15-20 minutes, or until they are fork-tender.",
      "Drain the potatoes in a colander, then return them to the pot.",
      "In a small saucepan, melt 4 tablespoons of butter and warm 125 ml of milk over low heat, stirring occasionally.",
      "Add the melted butter and warmed milk to the pot with the potatoes. Use a potato masher or an electric mixer to mash the potatoes until they reach your desired level of smoothness. Be careful not to overmix, as this can cause the potatoes to become gummy.",
      "Season the mashed potatoes with 1 teaspoon of salt and 1/2 teaspoon of pepper, adjusting the seasoning to taste.",
      "Optional: Add additional toppings such as chopped chives, spring onions, or a sprinkle of grated cheese if desired.",
      "Serve the Mustang Mashed Potatoes warm and enjoy!",
    ],
    dietTypes: ["VEGETARIAN"],
    reviews: [
      { author: "John", rating: 4, comment: "Delicious and creamy!" },
      { author: "Jane", rating: 5, comment: "My family loved it!" },
    ],
  },
  {
    id: 2,
    title: "Fiesta Fajitas",
    subtitle: "Drive your taste buds wild",
    cookingTimeInMins: 40,
    ingredients: [
      { ingredient: "Chicken", amount: 1, unit: "lb" },
      { ingredient: "Bell Peppers", amount: 3, unit: "medium" },
      { ingredient: "Onion", amount: 1, unit: "large" },
      { ingredient: "Fajita Seasoning", amount: 1, unit: "packet" },
      { ingredient: "Flour Tortillas", amount: 8, unit: "medium" },
    ],
    instructions: [
      "Slice 450 grams of chicken into thin strips.",
      "In a large frying pan, heat 2 tablespoons of oil over medium-high heat. Add the chicken and cook, stirring occasionally, until browned and cooked through (about 5-7 minutes). Transfer the cooked chicken to a plate and set aside.",
      "Slice the bell peppers and onion into thin strips.",
      "In the same frying pan, add another tablespoon of oil if needed, and cook the bell peppers and onion over medium-high heat until they are tender and slightly charred (about 5-6 minutes).",
      "Add the cooked chicken back to the frying pan with the peppers and onion.",
      "Sprinkle the fajita seasoning over the chicken and vegetables. Add 60 ml of water to the frying pan and stir to combine. Cook for an additional 2-3 minutes, or until the sauce has thickened.",
      "Warm the flour tortillas in the oven, microwave, or on a dry frying pan for a few seconds on each side.",
      "Serve the chicken and vegetable mixture in the warmed tortillas, along with your favourite toppings such as soured cream, guacamole, salsa, grated cheese, and chopped coriander.",
    ],
    dietTypes: ["HIGH_PROTEIN"],
    reviews: [
      { author: "Carlos", rating: 5, comment: "Amazing flavour!" },
      { author: "Maria", rating: 4, comment: "Great for a weeknight dinner!" },
    ],
  },
  {
    id: 3,
    title: "Expedition Aubergine Parmesan",
    subtitle: "Embark on a culinary adventure",
    cookingTimeInMins: 60,
    ingredients: [
      { ingredient: "Aubergine", amount: 1, unit: "large" },
      { ingredient: "Breadcrumbs", amount: 1, unit: "cup" },
      { ingredient: "Egg", amount: 2, unit: "large" },
      { ingredient: "Mozzarella", amount: 2, unit: "cups" },
      { ingredient: "Marinara Sauce", amount: 2, unit: "cups" },
      { ingredient: "Parmesan Cheese", amount: 0.5, unit: "cup" },
    ],
    instructions: [
      "Preheat the oven to 190°C (375°F) and grease a 23x33 cm (9x13-inch) baking dish.",
      "Wash and slice the aubergine into 0.6 cm (1/4-inch) thick rounds.",
      "Whisk the 2 large eggs in a shallow bowl. Place 1 cup of breadcrumbs in another shallow bowl.",
      "Dip each aubergine slice in the beaten eggs, allowing the excess to drip off. Then, coat each slice in breadcrumbs, pressing gently to help the breadcrumbs adhere.",
      "Place the breaded aubergine slices on a baking sheet in a single layer. Bake in the preheated oven for 20 minutes, flipping the slices halfway through, until they are golden and tender.",
      "Spread about 1 cup of marinara sauce in the bottom of the prepared baking dish.",
      "Layer half of the baked aubergine slices over the sauce, then top with 1 cup of mozzarella cheese and 1/4 cup of Parmesan cheese.",
      "Spread another cup of marinara sauce over the cheese layer, then arrange the remaining aubergine slices on top.",
      "Finish the dish with the remaining 1 cup of mozzarella cheese and 1/4 cup of Parmesan cheese.",
      "Bake the aubergine Parmesan in the oven for 25-30 minutes, or until the cheese is melted, bubbly, and slightly golden.",
      "Allow the dish to cool for 5-10 minutes before serving. Enjoy!",
    ],
    dietTypes: ["VEGETARIAN"],
    reviews: [
      { author: "Emily", rating: 5, comment: "A new family favourite!" },
      { author: "Olivia", rating: 4, comment: "Delicious and cheesy!" },
    ],
  },
  {
    id: 4,
    title: "Focus Frittata",
    subtitle: "Stay sharp with this protein-packed meal",
    cookingTimeInMins: 30,
    ingredients: [
      { ingredient: "Eggs", amount: 8, unit: "large" },
      { ingredient: "Spinach", amount: 2, unit: "cups" },
      { ingredient: "Tomato", amount: 1, unit: "large" },
      { ingredient: "Onion", amount: 1, unit: "small" },
      { ingredient: "Cheddar Cheese", amount: 1, unit: "cup" },
    ],
    instructions: [
      "Whisk eggs",
      "Sauté spinach, tomato, and onion",
      "Add veggies to eggs",
      "Pour mixture into pan",
      "Top with cheese",
      "Bake until set",
    ],
    dietTypes: ["HIGH_PROTEIN", "LOW_FAT", "GLUTEN_FREE"],
    reviews: [
      {
        author: "Mark",
        rating: 5,
        comment: "Perfect for breakfast or brunch!",
      },
      { author: "Lucy", rating: 4, comment: "Healthy and delicious!" },
    ],
  },
  {
    id: 5,
    title: "Ranger Roasted Vegetables",
    subtitle: "Off-road your way to healthy eating",
    cookingTimeInMins: 45,
    ingredients: [
      { ingredient: "Carrots", amount: 4, unit: "large" },
      { ingredient: "Courgette", amount: 2, unit: "medium" },
      { ingredient: "Bell Peppers", amount: 2, unit: "medium" },
      { ingredient: "Red Onion", amount: 1, unit: "large" },
      { ingredient: "Olive Oil", amount: 3, unit: "tbsp" },
      { ingredient: "Salt", amount: 1, unit: "tsp" },
      { ingredient: "Pepper", amount: 0.5, unit: "tsp" },
      { ingredient: "Garlic Powder", amount: 1, unit: "tsp" },
    ],
    instructions: [
      "Preheat oven to 220°C (425°F)",
      "Chop vegetables into bite-sized pieces",
      "Toss vegetables with olive oil, salt, pepper, and garlic powder",
      "Spread vegetables evenly on a baking tray",
      "Roast for 30-35 minutes, stirring occasionally, until tender and slightly caramelised",
    ],
    dietTypes: ["VEGETARIAN", "VEGAN", "GLUTEN_FREE", "NUT_FREE"],
    reviews: [
      { author: "Jake", rating: 5, comment: "So easy and flavourful!" },
      {
        author: "Sophie",
        rating: 4,
        comment: "A great side dish for any meal!",
      },
    ],
  },
];
